services:
  nivlheimweb:
    depends_on:
      - nivlheimapi
    image: ghcr.io/unioslo/nivlheim-www
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - data:/var/www/nivlheim
      - logs:/var/log
    environment:
      - NIVLHEIM_PGHOST=postgres
      - NIVLHEIM_PGUSER=nivlheim
      - NIVLHEIM_PGPASSWORD=notsecret
      - NIVLHEIM_PGDATABASE=nivlheim

  nivlheimapi:
    depends_on:
      postgres:
        condition: service_healthy
    image: ghcr.io/unioslo/nivlheim
    restart: always
    ports:
      - "4040:4040"
    volumes:
      - data:/var/www/nivlheim
      - logs:/var/log
    environment:
      - NIVLHEIM_PGHOST=postgres
      - NIVLHEIM_PGUSER=nivlheim
      - NIVLHEIM_PGPASSWORD=notsecret
      - NIVLHEIM_PGDATABASE=nivlheim
      - NIVLHEIM_PGSSLMODE=disable
      - NIVLHEIM_HTTPLISTENADDRESS=:4040

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=nivlheim
      - POSTGRES_DB=nivlheim
      - POSTGRES_PASSWORD=notsecret
    healthcheck:
      test: ["CMD", "pg_isready", "--username=nivlheim"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  data:
  logs:
