#!/usr/bin/perl
use strict;

print "Status: 200 OK\nContent-Type: text/plain\n\n";

print "User: ";
if (exists $ENV{'AUTHENTICATE_UID'}) {
	print $ENV{'AUTHENTICATE_UID'};
}
else {
	print $ENV{'REMOTE_USER'};
}

print "\n\n";
foreach my $key (keys %ENV) {
	if ($key =~ /^SSL/) {
		print "$key = " . $ENV{$key} . "\n";
	}
}
